package tasks.exceptions;

public class AuthException extends RuntimeException {
    
}
